# === Build Stage ===
FROM node:14-alpine AS build
WORKDIR /app

# Copy dependency files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Build the React app for production
RUN npm run build

# === Production Stage ===
FROM nginx:stable-alpine
# Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*
# Copy built React app from the previous stage
COPY --from=build /dist /usr/share/nginx/html

# Expose port 8080 to the outside world
EXPOSE 80

# Start Nginx server in the foreground
CMD ["nginx", "-g", "daemon off;"]